# see: https://goreleaser.com/customization/

project_name: snake
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: snake
    goos:
      - linux
      - darwin
      - windows
    # amd64 (64-bit x86)
    # 386 (32-bit x86)
    goarch:
      - amd64
      - 386
    goarm:
      - "6"
    ldflags: -s -w -X main.Version={{.Version}}  -X main.BuildDate={{.Date}}
archives:
  -
    # Defaults to `default`.
    id: snake
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
release:
  github:
    owner: qloog
    name: snake
  name_template: '{{.Tag}}'