# yaml 配置
version: "3.7"
services:
  app:
    container_name: app
    build: .
    environment:
      MYSQL_NAME: "snake"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "root"
      MYSQL_PASSWORD: "123456"
    depends_on:
      - "database"
    ports:
      - "8080:8080"
  database:
    container_name: db
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db.sql:/data/application/init.sql
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./conf/nginx_api.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'
