run_mode: debug                  # 开发模式, debug, release, test
addr: :8080                     # HTTP绑定端口
name: snake                    # API Server的名字
url: http://127.0.0.1:8080      # pingServer函数请求的API服务器的ip:port
max_ping_count: 10              # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: /data/logs/snake.log
  logger_warn_file: /data/logs/snake.wf.log
  logger_error_file: /data/logs/snake.err.log
  log_format_text: true
  log_rolling_policy: daily
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
gorm:
  show_log: true                  # 是否打印SQL日志
  max_idle_conn: 10               # 最大打开的连接数
  max_open_conn: 60               # 最大的闲置的连接数
  conn_max_life_time: 60          # 连接重用的最大时间，单位分钟
db:
  name: snake
  addr: 127.0.0.1:3306 # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  username: root
  password: 123456
docker_db:
  name: snake
  addr: 127.0.0.1:3306
  username: root
  password: 123456
redis:
  addr: "127.0.0.1:6379"
  password: "" # no password set
  db: 0 # use default DB
  dial_timeout: 30   # 单位：秒
  read_timeout: 10   # 单位：秒
  write_timeout: 10  # 单位：秒
  pool_size: 60
jaeger_open: 1
# 邮件发送配置
email:
  host: SMTP_HOST       # SMTP地址
  port: PORT            # 端口
  username: USER        # 用户名
  password: PASSWORD    # 密码
  name: snake           # 发送者名称
  address: SEND_EMAIL   # 发送者邮箱
  reply_to: EMAIL       # 回复地址
  keepalive: 30         # 连接保持时长
website:
  domain: snake.com
  name: snake
cache:
  driver: redis
  prefix: snake

