# trace config
ServiceName: "snake"
TraceAgent: "jaeger"
OpenDebug: "false"

Zipkin:
  HTTPEndpoint: "http://127.0.0.1:9411/api/v2/spans"
  SameSpan: false
  ID128Bit: true
  SampleRate: "1.0"
Jaeger:
  SamplingServerURL: "http://127.0.0.1:5778/sampling"
  SamplingType: "const"
  SamplingParam: "1.0"
  LocalAgentHostPort: "127.0.0.1:6831"
  Propagation: "jaeger"
  Gen128Bit: true
  TraceContextHeaderName: "uber-trace-id"
  CollectorEndpoint: ""
  CollectorUser: ""
  CollectorPassword: ""

# Elastic, only useful when TraceAgent is elastic
Elastic:
  ServerURL: "http://127.0.0.1:8200"
  SecretToken: ""
