name: Go
on:
  # 当代码推送到master和release分支的时候触发
  push:
    branches:
      - master
      - release/*
  # 当只有pull_request被合并到master分支的时候
  pull_request:
    branches:
      - master
  # 星期一到星期五的每天2点构建任务
  #schedule:
  #  - cron: 0 2 * * 1-5
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download
      env:
        GOPROXY: https://proxy.golang.org

    - name: Build
      run: go build -v .
